# This file was autogenerated by the BETA 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/from-1.5/variables#type-constraints for more info.

build {
  name = "build-ubuntu"
  sources = ["source.virtualbox-iso.ubuntu-vm"]

  source "virtualbox-iso.ubuntu-vm" {
    boot_command = [
        "<esc><wait>",
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/casper/vmlinuz",
        " auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/oem-preseed.cfg",
        " automatic-ubiquity",
        " debug-ubiquity",
        " keymap=us",
        " boot=casper initrd=/casper/initrd noprompt --",
        "<enter>"
    ]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | sudo -S sh -c '{{ .Vars }} {{ .Path }}'"
    inline          = [
      "echo STOPPING APT",
      "systemctl stop unattended-upgrades.service",
      "while(pgrep -a apt-get); do sleep 1; done",
      "export DEBIAN_FRONTEND=noninteractive",
      "echo UPDATE",
      "apt-get update",
      "echo INSTALL",
      "apt-get install -V -y git ansible aptitude",
      "git clone -b ${var.git_branch} ${var.git_repo}",
      "cd /home/${var.ssh_user}/cs-vm-build/scripts",
      "./oem-build",
      "/usr/sbin/oem-config-prepare"
    ]
  }

  post-processor "checksum" {
    checksum_types = ["sha256"]
    output         = "${local.output_dir}/image-${lower(var.semester)}.{{.ChecksumType}}sum"
  }
}
